config/routes.rb
Rails.application.routes.draw do
  resources :line_items do 
  
  end
  resources :orders

  devise_for :users
  resources :movies 
   root to: "movies#index"

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
  <div style="background-color: maroon;font-weight:bold; height:40px; color:white;padding:5px">
 <% if current_user %> 
<span><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, style: "float:right",class: "btn btn-danger" %></span>
<% else %>
<span style="float:right;margin-right:120px"><%= link_to 'Sign In',user_session_path, class: "btn btn-sm btn-primary",style: "border-radius:20px" %>
  </span>
  <% end %>
 <%= form_tag(movies_path, method: :get) do %>
<span style="float:right;margin-right:20px;"><%= text_field_tag :searchTerm %>
<%= submit_tag "Search",class: "btn btn-sm btn-success" %></span>
<% end %>
<span><%= link_to 'CoolFlix', movies_path %></span>

        <span style="float:right;margin-right:20px"> <%= link_to "Cart", line_items_path,class: "btn btn-sm btn-success" %></span>
        

    

  </div>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
 
    <%= yield %>
  </body>
</html>